//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSample.UI {
    
    public partial class EditPersonControl {
        protected Remotion.Web.UI.Controls.FormGridManager FormGridManager;
        protected Remotion.Data.DomainObjects.ObjectBinding.Web.DomainObjectDataSourceControl CurrentObject;
        protected System.Web.UI.HtmlControls.HtmlTable PersonFormGrid;
        protected Remotion.Web.UI.Controls.SmartLabel FirstNameLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocTextValue FirstNameField;
        protected Remotion.Web.UI.Controls.SmartLabel LastNameLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField;
        protected Remotion.Web.UI.Controls.SmartLabel EMailAddressLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocTextValue EMailAddressField;
        protected Remotion.Web.UI.Controls.SmartLabel LocationLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocReferenceValue LocationField;
        protected Remotion.Web.UI.Controls.SmartLabel PhoneNumbersLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocList PhoneNumbersField;
    }
}
