//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSample.UI {
    
    public partial class EditPersonForm {
        protected Remotion.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;
        protected System.Web.UI.HtmlControls.HtmlForm TheForm;
        protected Remotion.Data.DomainObjects.ObjectBinding.Web.DomainObjectDataSourceControl CurrentObject;
        protected Remotion.Web.UI.Controls.TabbedMultiView MultiView;
        protected WebSample.UI.NavigationTabs TheNavigationTabs;
        protected Remotion.Web.UI.Controls.TabView EditPersonView;
        protected WebSample.UI.EditPersonControl EditPersonControl;
        protected Remotion.Web.UI.Controls.WebButton SaveButton;
        protected Remotion.Web.UI.Controls.WebButton CancelButton;
    }
}
