// This file is part of the re-motion Core Framework (www.re-motion.org)
// Copyright (c) rubicon IT GmbH, www.rubicon.eu
// 
// The re-motion Core Framework is free software; you can redistribute it 
// and/or modify it under the terms of the GNU Lesser General Public License 
// as published by the Free Software Foundation; either version 2.1 of the 
// License, or (at your option) any later version.
// 
// re-motion is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with re-motion; if not, see http://www.gnu.org/licenses.
// 
using System;
using System.Globalization;
using System.Linq;
using NUnit.Framework;
using Remotion.Reflection;
using Remotion.Utilities;
using Remotion.Validation.Implementation;
using Remotion.Validation.IntegrationTests.TestDomain.ComponentA;
using Remotion.Validation.Rules;
using Remotion.Validation.Validators;

namespace Remotion.Validation.IntegrationTests
{
  [TestFixture]
  public class FluentValidationGlobalizationIntegrationTests : IntegrationTestBase
  {
    private PropertyValidationRule _propertyValidationRule;
    private Customer _customer;
    private PropertyInfoAdapter _property;

    /* Note: 
     *   > ValidationFailure.ErrorMessage displays a user-friendly property name (generated by PropertyRule.GetDisplayName) 
     *   > ValidationFailure.PropertyName represents the technical property name (generated by PropertyRule.BuildPropertyName)
     */

    public override void SetUp ()
    {
      base.SetUp();

      _property = PropertyInfoAdapter.Create (MemberInfoFromExpressionUtility.GetProperty ((Customer c) => c.LastName));
      var propertyValidators = new IPropertyValidator[] { new NotNullValidator() };
      _propertyValidationRule = new PropertyValidationRule (_property, propertyValidators);
      _customer = new Customer();
    }

    [Test]
    public void Validate_NoExplicitPropertyNameSet ()
    {
      var validationResult = _propertyValidationRule.Validate (new ValidationContext (_customer)).ToArray().First();

      Assert.That (validationResult.Property, Is.SameAs (_property));
      Assert.That (validationResult.ErrorMessage, Is.EqualTo ("Enter a value."));
    }

    [Test]
    public void DefaultErrorMessage_NotNullValidator ()
    {
      var validator = new NotNullValidator();

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.NotNullError));
    }

    [Test]
    public void DefaultErrorMessage_NotEmptyValidator ()
    {
      var validator = new NotEmptyValidator (null);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.NotEmptyError));
    }

    [Test]
    public void DefaultErrorMessage_NotEqualValidator ()
    {
      var validator = new NotEqualValidator (null);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.NotEqualError));
    }

    [Test]
    public void DefaultErrorMessage_EqualValidator ()
    {
      var validator = new EqualValidator (null);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.EqualError));
    }

    [Test]
    public void DefaultErrorMessage_ExactLengthValidator ()
    {
      var validator = new ExactLengthValidator (10);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.ExactLengthError));
    }

    [Test]
    public void DefaultErrorMessage_MaxLengthValidator ()
    {
      var validator = new LengthValidator (1, 3);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.LengthError));
    }

    [Test]
    public void DefaultErrorMessage_ExclusiveBetweenValidator ()
    {
      var validator = new ExclusiveBetweenValidator (1, 3);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.ExclusiveBetweenError));
    }

    [Test]
    public void DefaultErrorMessage_InclusiveBetweenValidator ()
    {
      var validator = new InclusiveBetweenValidator (1, 3);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.InclusiveBetweenError));
    }

    [Test]
    public void DefaultErrorMessage_LessThanValidator ()
    {
      var validator = new LessThanValidator (1);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.LessThanError));
    }

    [Test]
    public void DefaultErrorMessage_LessThanOrEqualValidator ()
    {
      var validator = new LessThanOrEqualValidator (1);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.LessThanOrEqualError));
    }

    [Test]
    public void DefaultErrorMessage_GreaterThanValidator ()
    {
      var validator = new GreaterThanValidator (1);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.GreaterThanError));
    }

    [Test]
    public void DefaultErrorMessage_GreaterThanOrEqualValidator ()
    {
      var validator = new GreaterThanOrEqualValidator (1);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.GreaterThanOrEqualError));
    }

    [Test]
    public void DefaultErrorMessage_PredicateValidator ()
    {
      var validator = new PredicateValidator ((o1, o2, o3) => true);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.PredicateError));
    }

    [Test]
    public void DefaultErrorMessage_RegularExpressionValidator ()
    {
      var validator = new RegularExpressionValidator ("");

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.RegularExpressionError));
    }

    [Test]
    public void DefaultErrorMessage_ScalePrecisionValidator ()
    {
      var validator = new ScalePrecisionValidator (2, 5);

      Assert.That (validator.ValidationMessage.ToString (CultureInfo.InvariantCulture), Is.EqualTo (Constants.ScalePrecisionError));
    }
  }
}