// This file is part of the re-motion Core Framework (www.re-motion.org)
// Copyright (C) 2005-2008 rubicon informationstechnologie gmbh, www.rubicon.eu
// 
// The re-motion Core Framework is free software; you can redistribute it 
// and/or modify it under the terms of the GNU Lesser General Public License 
// version 3.0 as published by the Free Software Foundation.
// 
// re-motion is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with re-motion; if not, see http://www.gnu.org/licenses.
// 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBWTest.IndividualControlTests {
    
    public partial class BocAutoCompleteReferenceValueUserControl {
        protected Remotion.Web.UI.Controls.FormGridManager FormGridManager;
        protected Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
        protected System.Web.UI.HtmlControls.HtmlTable FormGrid;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocTextValue FirstNameField;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue PartnerField;
        protected System.Web.UI.WebControls.Label PartnerFieldValueLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue ReadOnlyPartnerField;
        protected System.Web.UI.WebControls.Label ReadOnlyPartnerFieldValueLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue UnboundPartnerField;
        protected System.Web.UI.WebControls.Label UnboundPartnerFieldValueLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue UnboundReadOnlyPartnerField;
        protected System.Web.UI.WebControls.Label UnboundReadOnlyPartnerFieldValueLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue DisabledPartnerField;
        protected System.Web.UI.WebControls.Label DisabledPartnerFieldValueLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue DisabledReadOnlyPartnerField;
        protected System.Web.UI.WebControls.Label DisabledReadOnlyPartnerFieldValueLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue DisabledUnboundPartnerField;
        protected System.Web.UI.WebControls.Label DisabledUnboundPartnerFieldValueLabel;
        protected Remotion.ObjectBinding.Web.UI.Controls.BocAutoCompleteReferenceValue DisabledUnboundReadOnlyPartnerField;
        protected System.Web.UI.WebControls.Label DisabledUnboundReadOnlyPartnerFieldValueLabel;
        protected System.Web.UI.WebControls.Label PartnerCommandClickLabel;
        protected System.Web.UI.WebControls.Label PartnerFieldSelectionChangedLabel;
        protected System.Web.UI.WebControls.Label PartnerFieldMenuClickEventArgsLabel;
        protected Remotion.Web.UI.Controls.WebButton PartnerTestSetNullButton;
        protected Remotion.Web.UI.Controls.WebButton PartnerTestSetNewItemButton;
        protected Remotion.Web.UI.Controls.WebButton ReadOnlyPartnerTestSetNullButton;
        protected Remotion.Web.UI.Controls.WebButton ReadOnlyPartnerTestSetNewItemButton;
    }
}
