// This file is part of the re-motion Core Framework (www.re-motion.org)
// Copyright (c) rubicon IT GmbH, www.rubicon.eu
// 
// The re-motion Core Framework is free software; you can redistribute it 
// and/or modify it under the terms of the GNU Lesser General Public License 
// as published by the Free Software Foundation; either version 2.1 of the 
// License, or (at your option) any later version.
// 
// re-motion is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with re-motion; if not, see http://www.gnu.org/licenses.
// 
using System;
using Remotion.Mixins.CodeGeneration.DynamicProxy;
using Remotion.Mixins.Context;

namespace Remotion.Mixins.CodeGeneration
{
  /// <summary>
  /// Provides a common interface for classes used to get concrete types for the mixin configuration.
  /// </summary>
  public interface IConcreteTypeBuilder : IConcreteTypeProvider, IConcreteMixinTypeProvider
  {
    /// <summary>
    /// Saves the assemblies generated by this <see cref="IConcreteTypeBuilder"/> to disk and resets the builder, so that it can continue to generate 
    /// types. 
    /// </summary>
    /// <returns>An array containing the paths of the assembly files saved.</returns>
    /// <remarks>
    /// <para>
    /// Each time this method is called, only the types generated since the last save operation are persisted.
    /// </para>
    /// <para>
    /// Having different assemblies with the same names loaded into one AppDomain can lead to sporadic
    /// <see cref="TypeLoadException">TypeLoadExceptions</see> in reflective scenarios. To avoid such errors, the  
    /// <see cref="ModuleManager.SignedAssemblyName"/> and <see cref="ModuleManager.UnsignedAssemblyName"/> properties by default include a counter
    /// that is increased every time the scope is reset; that way, the assembly names change every time.
    /// </para>
    /// </remarks>
    string[] SaveAndResetDynamicScope ();
  }
}
