//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.UI {
    
    
    /// <summary>
    /// SecurityManagerNavigationTabs class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class SecurityManagerNavigationTabs {
        
        /// <summary>
        /// SecurityManagerCurrentTenantControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.SecurityManager.Clients.Web.UI.CurrentTenantControl SecurityManagerCurrentTenantControl;
        
        /// <summary>
        /// TabbedMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.TabbedMenu TabbedMenu;
    }
}
