/* Copyright (C) 2005 - 2008 rubicon informationstechnologie gmbh
 *
 * This program is free software: you can redistribute it and/or modify it under 
 * the terms of the re:motion license agreement in license.txt. If you did not 
 * receive it, please visit http://www.re-motion.org/licensing.
 * 
 * Unless otherwise provided, this software is distributed on an "AS IS" basis, 
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.UI {
    
    public partial class SecurityManagerMasterPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head;
        protected System.Web.UI.HtmlControls.HtmlForm ThisForm;
        protected System.Web.UI.WebControls.ContentPlaceHolder HeaderControlsPlaceHolder;
        protected Remotion.SecurityManager.Clients.Web.UI.SecurityManagerNavigationTabs SecurityManagerNavigationTabs;
        protected System.Web.UI.WebControls.ContentPlaceHolder TopControlsPlaceHolder;
        protected System.Web.UI.WebControls.ContentPlaceHolder MainContentPlaceHolder;
        protected System.Web.UI.WebControls.ContentPlaceHolder BottomControlsPlaceHolder;
    }
}
