//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.UI {
    
    public partial class SecurityManagerMasterPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head;
        protected System.Web.UI.HtmlControls.HtmlForm ThisForm;
        protected System.Web.UI.WebControls.ContentPlaceHolder HeaderControlsPlaceHolder;
        protected Remotion.SecurityManager.Clients.Web.UI.SecurityManagerNavigationTabs SecurityManagerNavigationTabs;
        protected System.Web.UI.WebControls.ContentPlaceHolder TopControlsPlaceHolder;
        protected System.Web.UI.WebControls.ContentPlaceHolder MainContentPlaceHolder;
        protected System.Web.UI.WebControls.ContentPlaceHolder BottomControlsPlaceHolder;
    }
}
