//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.Globalization.UI.AccessControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remotion.SecurityManager.Clients.Web.Globalization.UI.AccessControl.AccessControl" +
                            "Resources", typeof(AccessControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACE (Access Control Entry).
        /// </summary>
        internal static string auto_AccessControlEntryTitle_InnerText {
            get {
                return ResourceManager.GetString("auto:AccessControlEntryTitle:InnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all permissions.
        /// </summary>
        internal static string auto_AllPermissionsLabel_Text {
            get {
                return ResourceManager.GetString("auto:AllPermissionsLabel:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign at least one state..
        /// </summary>
        internal static string auto_MissingStateCombinationsValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:MissingStateCombinationsValidator:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string auto_PermissionsLabel_Text {
            get {
                return ResourceManager.GetString("auto:PermissionsLabel:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a state..
        /// </summary>
        internal static string auto_RequiredStateCombinationValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:RequiredStateCombinationValidator:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group..
        /// </summary>
        internal static string auto_SpecificGroupField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificGroupField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group type..
        /// </summary>
        internal static string auto_SpecificGroupTypeField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificGroupTypeField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a position..
        /// </summary>
        internal static string auto_SpecificPositionField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificPositionField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a tenant..
        /// </summary>
        internal static string auto_SpecificTenantField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificTenantField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user..
        /// </summary>
        internal static string auto_SpecificUserField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificUserField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object-based ACL (Access Control List).
        /// </summary>
        internal static string auto_StatefulAccessControlListTitle_InnerText {
            get {
                return ResourceManager.GetString("auto:StatefulAccessControlListTitle:InnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class-based ACL (Access Control List).
        /// </summary>
        internal static string auto_StatelessAccessControlListTitle_InnerText {
            get {
                return ResourceManager.GetString("auto:StatelessAccessControlListTitle:InnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ACE.
        /// </summary>
        internal static string DeleteAccessControlEntryButton {
            get {
                return ResourceManager.GetString("DeleteAccessControlEntryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ACL.
        /// </summary>
        internal static string DeleteAccessControlListButton {
            get {
                return ResourceManager.GetString("DeleteAccessControlListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove State.
        /// </summary>
        internal static string DeleteStateCombinationCommand {
            get {
                return ResourceManager.GetString("DeleteStateCombinationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States must be unqiue within the ACL..
        /// </summary>
        internal static string DuplicateStateCombinationsValidatorErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateStateCombinationsValidatorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ACE.
        /// </summary>
        internal static string NewAccessControlEntryButton {
            get {
                return ResourceManager.GetString("NewAccessControlEntryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign State.
        /// </summary>
        internal static string NewStateCombinationButton {
            get {
                return ResourceManager.GetString("NewStateCombinationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object-based ACL.
        /// </summary>
        internal static string NewStatefulAccessControlListButton {
            get {
                return ResourceManager.GetString("NewStatefulAccessControlListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New class-based ACL.
        /// </summary>
        internal static string NewStatelessAccessControlListButton {
            get {
                return ResourceManager.GetString("NewStatelessAccessControlListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Edit Permissions.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
