//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.Globalization.UI.AccessControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remotion.SecurityManager.Clients.Web.Globalization.UI.AccessControl.AccessControl" +
                            "Resources", typeof(AccessControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        internal static string AllPermissionsMenu_ClearAllPermissions_Text {
            get {
                return ResourceManager.GetString("AllPermissionsMenu:ClearAllPermissions:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny all.
        /// </summary>
        internal static string AllPermissionsMenu_DenyAllPermissions_Text {
            get {
                return ResourceManager.GetString("AllPermissionsMenu:DenyAllPermissions:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant all.
        /// </summary>
        internal static string AllPermissionsMenu_GrantAllPermissions_Text {
            get {
                return ResourceManager.GetString("AllPermissionsMenu:GrantAllPermissions:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ACL.
        /// </summary>
        internal static string auto_DeleteAccessControlListButton_Text {
            get {
                return ResourceManager.GetString("auto:DeleteAccessControlListButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign at least one state..
        /// </summary>
        internal static string auto_MissingStateCombinationsValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:MissingStateCombinationsValidator:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row.
        /// </summary>
        internal static string auto_NewAccessControlEntryButton_Text {
            get {
                return ResourceManager.GetString("auto:NewAccessControlEntryButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign State.
        /// </summary>
        internal static string auto_NewStateCombinationButton_Text {
            get {
                return ResourceManager.GetString("auto:NewStateCombinationButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a state..
        /// </summary>
        internal static string auto_RequiredStateCombinationValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:RequiredStateCombinationValidator:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group..
        /// </summary>
        internal static string auto_SpecificGroupField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificGroupField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group type..
        /// </summary>
        internal static string auto_SpecificGroupTypeField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificGroupTypeField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a position..
        /// </summary>
        internal static string auto_SpecificPositionField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificPositionField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a tenant..
        /// </summary>
        internal static string auto_SpecificTenantField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificTenantField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user..
        /// </summary>
        internal static string auto_SpecificUserField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificUserField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within same.
        /// </summary>
        internal static string BranchOfOwningGroupLabel {
            get {
                return ResourceManager.GetString("BranchOfOwningGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        internal static string CollapseAccessControlEntryButton_Text {
            get {
                return ResourceManager.GetString("CollapseAccessControlEntryButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row.
        /// </summary>
        internal static string DeleteAccessControlEntryButton_Text {
            get {
                return ResourceManager.GetString("DeleteAccessControlEntryButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove State.
        /// </summary>
        internal static string DeleteStateCombinationButton_Text {
            get {
                return ResourceManager.GetString("DeleteStateCombinationButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States must be unqiue within the ACL..
        /// </summary>
        internal static string DuplicateStateCombinationsValidatorErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateStateCombinationsValidatorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ExpandAccessControlEntryButton_Text {
            get {
                return ResourceManager.GetString("ExpandAccessControlEntryButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any.
        /// </summary>
        internal static string GroupCondition_None {
            get {
                return ResourceManager.GetString("GroupCondition.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only this group.
        /// </summary>
        internal static string GroupHierarchyCondition_This {
            get {
                return ResourceManager.GetString("GroupHierarchyCondition.This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group or children.
        /// </summary>
        internal static string GroupHierarchyCondition_ThisAndChildren {
            get {
                return ResourceManager.GetString("GroupHierarchyCondition.ThisAndChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group or parents.
        /// </summary>
        internal static string GroupHierarchyCondition_ThisAndParent {
            get {
                return ResourceManager.GetString("GroupHierarchyCondition.ThisAndParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group or parents or children.
        /// </summary>
        internal static string GroupHierarchyCondition_ThisAndParentAndChildren {
            get {
                return ResourceManager.GetString("GroupHierarchyCondition.ThisAndParentAndChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add object-based ACL.
        /// </summary>
        internal static string NewStatefulAccessControlListButton_Text {
            get {
                return ResourceManager.GetString("NewStatefulAccessControlListButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add class-based ACL.
        /// </summary>
        internal static string NewStatelessAccessControlListButton_Text {
            get {
                return ResourceManager.GetString("NewStatelessAccessControlListButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;-access denied.
        /// </summary>
        internal static string PermissionDenied_Text {
            get {
                return ResourceManager.GetString("PermissionDenied:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;-access granted.
        /// </summary>
        internal static string PermissionGranted_Text {
            get {
                return ResourceManager.GetString("PermissionGranted:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;-access not set.
        /// </summary>
        internal static string PermissionUndefined_Text {
            get {
                return ResourceManager.GetString("PermissionUndefined:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object-based permissions.
        /// </summary>
        internal static string StatefulAccessControlListsTitle {
            get {
                return ResourceManager.GetString("StatefulAccessControlListsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class-based permissions.
        /// </summary>
        internal static string StatelessAccessControlListTitle {
            get {
                return ResourceManager.GetString("StatelessAccessControlListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any.
        /// </summary>
        internal static string TenantCondition_None {
            get {
                return ResourceManager.GetString("TenantCondition.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only this tenant.
        /// </summary>
        internal static string TenantHierarchyCondition_This {
            get {
                return ResourceManager.GetString("TenantHierarchyCondition.This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tenant or parents.
        /// </summary>
        internal static string TenantHierarchyCondition_ThisAndParent {
            get {
                return ResourceManager.GetString("TenantHierarchyCondition.ThisAndParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permissions for class &apos;{0}&apos;.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any.
        /// </summary>
        internal static string UserCondition_None {
            get {
                return ResourceManager.GetString("UserCondition.None", resourceCulture);
            }
        }
    }
}
