/* Copyright (C) 2005 - 2008 rubicon informationstechnologie gmbh
 *
 * This program is free software: you can redistribute it and/or modify it under 
 * the terms of the re:motion license agreement in license.txt. If you did not 
 * receive it, please visit http://www.re-motion.org/licensing.
 * 
 * Unless otherwise provided, this software is distributed on an "AS IS" basis, 
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.Globalization.UI.AccessControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remotion.SecurityManager.Clients.Web.Globalization.UI.AccessControl.AccessControl" +
                            "Resources", typeof(AccessControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Priority: {0}.
        /// </summary>
        internal static string ActualPriorityLabelText {
            get {
                return ResourceManager.GetString("ActualPriorityLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACE (Access Control Entry).
        /// </summary>
        internal static string auto_AccessControlEntryTitle_InnerText {
            get {
                return ResourceManager.GetString("auto:AccessControlEntryTitle:InnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL (Access Control List).
        /// </summary>
        internal static string auto_AccessControlListTitle_InnerText {
            get {
                return ResourceManager.GetString("auto:AccessControlListTitle:InnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign at least one state..
        /// </summary>
        internal static string auto_MissingStateCombinationsValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:MissingStateCombinationsValidator:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string auto_PermissionsLabel_Text {
            get {
                return ResourceManager.GetString("auto:PermissionsLabel:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a tenant..
        /// </summary>
        internal static string auto_SpecificTenantField_ErrorMessage {
            get {
                return ResourceManager.GetString("auto:SpecificTenantField:ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ACE.
        /// </summary>
        internal static string DeleteAccessControlEntryButton {
            get {
                return ResourceManager.GetString("DeleteAccessControlEntryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ACL.
        /// </summary>
        internal static string DeleteAccessControlListButton {
            get {
                return ResourceManager.GetString("DeleteAccessControlListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove State.
        /// </summary>
        internal static string DeleteStateCombinationCommand {
            get {
                return ResourceManager.GetString("DeleteStateCombinationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States must be unqiue within the ACL..
        /// </summary>
        internal static string DuplicateStateCombinationsValidatorErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateStateCombinationsValidatorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ACE.
        /// </summary>
        internal static string NewAccessControlEntryButton {
            get {
                return ResourceManager.GetString("NewAccessControlEntryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ACL.
        /// </summary>
        internal static string NewAccessControlListButton {
            get {
                return ResourceManager.GetString("NewAccessControlListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign State.
        /// </summary>
        internal static string NewStateCombinationButton {
            get {
                return ResourceManager.GetString("NewStateCombinationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string SpecificPositionAndGroupLinkingLabelText {
            get {
                return ResourceManager.GetString("SpecificPositionAndGroupLinkingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Edit Permissions.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
