/* Copyright (C) 2005 - 2008 rubicon informationstechnologie gmbh
 *
 * This program is free software: you can redistribute it and/or modify it under 
 * the terms of the re:motion license agreement in license.txt. If you did not 
 * receive it, please visit http://www.re-motion.org/licensing.
 * 
 * Unless otherwise provided, this software is distributed on an "AS IS" basis, 
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Remotion.SecurityManager.Globalization.Domain.AccessControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class TenantSelection {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenantSelection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Remotion.SecurityManager.Globalization.Domain.AccessControl.TenantSelection", typeof(TenantSelection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Tenant.
        /// </summary>
        internal static string Remotion_SecurityManager_Domain_AccessControl_TenantSelection_All {
            get {
                return ResourceManager.GetString("Remotion.SecurityManager.Domain.AccessControl.TenantSelection.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant of the Object or parents.
        /// </summary>
        internal static string Remotion_SecurityManager_Domain_AccessControl_TenantSelection_OwningTenant {
            get {
                return ResourceManager.GetString("Remotion.SecurityManager.Domain.AccessControl.TenantSelection.OwningTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Tenant.
        /// </summary>
        internal static string Remotion_SecurityManager_Domain_AccessControl_TenantSelection_SpecificTenant {
            get {
                return ResourceManager.GetString("Remotion.SecurityManager.Domain.AccessControl.TenantSelection.SpecificTenant", resourceCulture);
            }
        }
    }
}
