/* Copyright (C) 2005 - 2008 rubicon informationstechnologie gmbh
 *
 * This program is free software: you can redistribute it and/or modify it under 
 * the terms of the re:motion license agreement in license.txt. If you did not 
 * receive it, please visit http://www.re-motion.org/licensing.
 * 
 * Unless otherwise provided, this software is distributed on an "AS IS" basis, 
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. 
 */

//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace $PROJECT_ROOTNAMESPACE$.UI
{
	public partial class Edit$DOMAIN_CLASSNAME$Form
	{
		protected Remotion.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;

		protected $PROJECT_ROOTNAMESPACE$.UI.NavigationTabs TheNavigationTabs;
    protected Remotion.Web.UI.Controls.TabbedMultiView MultiView;
		protected Remotion.Web.UI.Controls.TabView Edit$DOMAIN_CLASSNAME$View;
		protected $PROJECT_ROOTNAMESPACE$.UI.Edit$DOMAIN_CLASSNAME$Control Edit$DOMAIN_CLASSNAME$Control;
		protected System.Web.UI.HtmlControls.HtmlForm ThisForm;
		protected Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
		protected Remotion.Web.UI.Controls.WebButton SaveButton;
		protected Remotion.Web.UI.Controls.WebButton CancelButton;
	}
}
