//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace $PROJECT_ROOTNAMESPACE$.UI
{
	public partial class SearchResult$DOMAIN_CLASSNAME$Form
	{
		protected Remotion.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;
		protected Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl $DOMAIN_CLASSNAME$SearchDataSource;
		protected Remotion.Web.UI.Controls.FormGridManager FormGridManager;
		protected $PROJECT_ROOTNAMESPACE$.UI.NavigationTabs NavigationTabs;
		protected Remotion.ObjectBinding.Web.UI.Controls.BocList $DOMAIN_CLASSNAME$List;
	}
}
