/* Copyright (C) 2005 - 2008 rubicon informationstechnologie gmbh
 *
 * This program is free software: you can redistribute it and/or modify it under 
 * the terms of the re:motion license agreement in license.txt. If you did not 
 * receive it, please visit http://www.re-motion.org/licensing.
 * 
 * Unless otherwise provided, this software is distributed on an "AS IS" basis, 
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.UI.OrganizationalStructure {
    
    public partial class EditRoleForm {
        protected Remotion.SecurityManager.Clients.Web.UI.ErrorMessageControl ErrorMessageControl;
        protected Remotion.SecurityManager.Clients.Web.UI.OrganizationalStructure.EditRoleControl EditRoleControl;
        protected Remotion.Web.UI.Controls.WebButton CloseButton;
        protected Remotion.Web.UI.Controls.WebButton CancelButton;
    }
}
