/* Copyright (C) 2005 - 2008 rubicon informationstechnologie gmbh
 *
 * This program is free software: you can redistribute it and/or modify it under 
 * the terms of the re:motion license agreement in license.txt. If you did not 
 * receive it, please visit http://www.re-motion.org/licensing.
 * 
 * Unless otherwise provided, this software is distributed on an "AS IS" basis, 
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. 
 */

using System;

namespace Remotion.Mixins
{
  /// <summary>
  /// Defines the visibility of members generated by the mixin infrastructure.
  /// </summary>
  public enum MemberVisibility
  {
    /// <summary>
    /// The members are generated private.
    /// </summary>
    Private,
    /// <summary>
    /// The members are generated public.
    /// </summary>
    Public
  }
}